# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPostrelativepath():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_postrelativepath(self):
    self.driver.get("https://www.facebook.com/tuna.gul.1238")
    self.driver.set_window_size(1900, 1060)
    self.driver.execute_script("window.scrollTo(0,150)")
    self.driver.execute_script("window.scrollTo(0,344)")
    self.driver.find_element(By.XPATH, "//div[2]/div/div[2]/div/div/div/div/div/div/div/span").click()
    element = self.driver.find_element(By.XPATH, "//form/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<div data-contents=\"true\"><div class=\"\" data-block=\"true\" data-editor=\"ovfl\" data-offset-key=\"cp8ig-0-0\"><div data-offset-key=\"cp8ig-0-0\" class=\"_1mf _1mj\"><span data-offset-key=\"cp8ig-0-0\"><span data-text=\"true\">deneme</span></span></div></div></div>'}", element)
    self.driver.find_element(By.XPATH, "//form/div/div/div/div/div[3]/div[2]/div").click()
  
